[package]
name = "visa-rs"
version = "0.1.0"
authors = ["ITOAR <itoar@outlook.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/TsuITOAR/visa-rs"
homepage = "https://github.com/TsuITOAR/visa-rs"
description = "Safe rust bindings for VISA(Virtual Instrument Software Architecture) library"
exclude = ["/expand.rs", "/fetch-doc"]

[dependencies]
visa-sys = "^0.1"
bitflags = "^1.3"
num_enum = "^0.5"
visa-rs-proc = { version = "^0.1", path = "./visa-rs-proc" }
log = "^0.4"

[dev-dependencies]
anyhow = "*"
tokio = { version = "*", features = ["rt-multi-thread"] }
env_logger = "*"


[patch.crates-io]
visa-sys = { path = "../visa-sys" }
