[package]
name = "visa-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
visa-sys = "*"
bitflags = "^1.3"
enum-kinds = "^0.5"
num_enum = "^0.5"
visa-rs-proc = { path = "./visa-rs-proc" }
log = "^0.4"

[dev-dependencies]
anyhow = "*"
tokio = { version = "*", features = ["rt-multi-thread"] }
env_logger = "*"


[patch.crates-io]
visa-sys = { path = "../visa-sys" }
